### ISSUE TITLE
Evaluate and choose a date-picker widget

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#14]
More detailed interactions available in design documents.

![screen shot 2015-04-01 at 2 44 36 pm](https://cloud.githubusercontent.com/assets/96776/6953363/b1661b9a-d87d-11e4-87be-aaa82272063f.png)

**Comment by jvine** [comment]
This is the recommended solution:
http://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html

It is keyboard and screen-reader accessible. If a native HTML5 control is available, it uses that; otherwise it pops up a calendar that looks like this:
![screen shot 2015-04-22 at 5 48 42 pm](https://cloud.githubusercontent.com/assets/6945691/7288537/e8e6119c-e917-11e4-8706-5b24e902dd8e.png)
![screen shot 2015-04-22 at 5 48 52 pm](https://cloud.githubusercontent.com/assets/6945691/7288538/edcfb6d6-e917-11e4-931e-a65a1a2ecb93.png)

We can set a min and max value - so it meets
•  earliest selectable date is based on delivery schedule + time of request
•  cannot select a date more than 1 year in future

but not
•  cannot select date when the library is closed

so we will need some error trapping for weekends and other known closed days.

**Comment by jvine** [comment]
There is another solution that is fully accessible AND can disable specific dates, which may solve the remaining issue. 

See: https://github.com/accdc/tsg
Documentation is here: http://whatsock.com/tsg/#tgl-2-3
The developer seems really open to answering questions.

**Comment by jvine** [comment]
Just so it's clear, we're planning to implement this one:
http://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html
