### ISSUE TITLE
Place title level holds for on-order items

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1450]
We need to place title-level holds for some types of requests we send to FOLIO. 

One type that's new for us with FOLIO is instances that don't have items yet (like some types of on-order). There is [some similar logic](https://github.com/sul-dlss/sul-requests/blob/master/app/jobs/submit_symphony_request_job.rb#L215) on the Symphony job for placing title-level requests for items where the user didn't/can't provide a barcode.

Not yet in scope for this is placing title-level holds for all types of hold/recall requests (existing behavior) which needs some more thinking (e.g. #1453) first.

**Comment by thatbudakguy** [comment]
Waiting until we have on-order items migrated to do this.

**Comment by jcoyne** [comment]
Related to this, I'm trying to make a request for an on-order item (https://searchworks-folio-dev.stanford.edu/view/14724231) and it links to "origin=ZOMBIE". This ends up triggering this rule, which sends a HB notification:
https://github.com/sul-dlss/sul-requests/blob/main/config/settings.yml#L627-L629

I'm wondering if we should add a rule for the ZOMBIE location so that we don't get a HB notification when we request an on order title.

**Comment by jcoyne** [comment]
We will not do anything around ZOMBIE location for now because this will be replaced by circ rules.
