### ISSUE TITLE
Map Symphony's user statuses to FOLIO data

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1460]
Symphony has several user statuses that impact the kind of error handling/reporting we do:

- ACTIVE
- DELINQUENT
- BLOCKED
- BARRED

and some inferred state or groups:
- expired
- fee borrower

How are these expressed in FOLIO? Do the equivalent states need any special handling from us?

**Comment by thatbudakguy** [comment]
@saseestone to explain the different statuses and what they mean

**Comment by cbeer** [comment]
I think FOLIO doesn't have the same notion of user status. We have

`patron.active`

and then some notion of automatic (driven by state; e.g. has too many fines) and manual blocks (library-staff entered). Automatic blocks specify what a patron can't do (blockRequests/blockRenewals/blockBorrowing..) and have a message. Manual blocks are kinda similar.

We can possibly show the automatic block message(s) to the patron as part of an error message or factor the `blockRequests` flag into our existing status checks.

Manual blocks may have a `patronMessage` and some other flags, but it seems a little less controlled.

**Comment by thatbudakguy** [comment]
sarah will investigate what the UX is from the staff side around editing patron notices/block messages/etc.

**Comment by saseestone** [comment]
Users receive "Patron blocks" because their record has met a "condition". Conditions include: 
- Maximum number of items charged out
- Maximum number of lost items
- Maximum number of overdue items
- Maximum number of overdue recalls
- Maximum outstanding fee/fine balance
- Recall overdue by maximum number of days

And no, I can't see any codes or names for those conditions in the Folio UI. Just the phrases. 

Each condition comes with pre-set blocks. There are three possible pre-set blocks:
1. Block borrowing
2. Block renewals
3. Block request

Each condition also has a required "Message to be displayed" field. 

Here is how the conditions are currently set:
- Maximum number of items charged out
-- Block borrowing 
-- Message to be displayed = You have reached the maximum number of items you are allowed to check out. Your account is blocked.

- Maximum number of lost items
-- Block borrowing
-- Block renewals
-- Message to be displayed = Your account shows lost materials. Your account is blocked.

- Maximum number of overdue items
-- Block borrowing
-- Message to be displayed = You have reached the maximum number of overdue library materials. Your account is blocked.

- Maximum number of overdue recalls
-- Block borrowing
-- Message to be displayed = You have recalled library materials that must be returned. Your account is blocked.

- Maximum outstanding fee/fine balance
-- Block borrowing
-- Block renewals
-- Message to be displayed = You have fees and fines to pay. Your account is blocked

- Recall overdue by maximum number of days (maybe delivered by FOLIO as a preset that we don't use at Stanford?)
-- (no blocks)
-- (no Message to be displayed)

**Comment by saseestone** [comment]
Additionally, library staff can create a user block within the FOLIO UI. When they do that, they apply a Patron block template. Here are the current templates:
- Bad physical address/email
- Card lost
- ILL block
- Permanent block

The templates automatically assign "Block actions", but they can be edited by the staff member creating the block. In each template, all three possible pre-set blocks are selected (e.g. "Block borrowing", "Block renewals" and "Block requests"). 

Each template also has a field for "Display description" and "Message to patron" but both fields are currently blank. There is also a field for a "Block code" but that field is currently blank.
<img width="1452" alt="image" src="https://github.com/sul-dlss/sul-requests/assets/14897546/add07c19-4064-472c-80e5-07526fe10e3c">

These blocks are characterized in the UI as Type = Manual
<img width="756" alt="image" src="https://github.com/sul-dlss/sul-requests/assets/14897546/bf4bd736-da91-488e-87ba-e8a9a21c247f">

**Comment by saseestone** [comment]
In a scary turn of events, Library staff can create Patron blocks that don't have a template defined.  They do have to include a  "Display description" but as long as they input that required field + specify the block actions, they can create any type of block.
<img width="759" alt="image" src="https://github.com/sul-dlss/sul-requests/assets/14897546/f2c70cc0-17ad-4bf0-acb0-f0932aa2fc6d">

**Comment by thatbudakguy** [comment]
We think this was mostly handled as part of the "use bib data from FOLIO" work.
