### ISSUE TITLE
User is blocked, but request placed with pseudo.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-requests#1558]
Request is being placed for HOLD@XX psuedo rather than the user account
https://searchworks-folio-dev.stanford.edu/view/14600413

From https://docs.google.com/spreadsheets/d/1D6M-m1IYNakKPfHfH0072tImrFY6x-yKfhu6bvGpVSI/edit?pli=1#gid=1019581243

**Comment by jcoyne** [comment]
@saseestone with FOLIO we can see the user has blocks. This means we can prevent the patron from making a request and let them know why on the web page, rather than allow them to make a request and then send them an error email as we presently do with Symphony. This seems like a much better user experience.  Should we do this instead?

**Comment by cbeer** [comment]
I don't this we can yet -- at least in Symphony land, we don't have the patron information until after the request ends up in the sidekiq queue (very intentionally, because Symphony has scheduled down time.).

Even after FOLIO, we haven't actually authenticated the patron if they entered a barcode, so we wouldn't want to leak patron status in the UI.

**Comment by jcoyne** [comment]
It looks like the ticket for this is #1527 and I don't see that it has been completed yet.
