### ISSUE TITLE
[sul-requests/prod] NoMethodError: undefined method `library_id' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-requests#1770]
## Backtrace

    line 39 of [PROJECT_ROOT]/app/models/folio/service_point.rb: library_id
    line 29 of [PROJECT_ROOT]/app/models/folio/service_point.rb: library
    line 30 of [PROJECT_ROOT]/app/models/folio/pickup_destination.rb: library_code

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49963/faults/99760209)

**Comment by hudajkhan** [comment]
In the case of RWC, the FOLIO pickup destination class tries to look up library code.  RWC is a service point with no associated location or library.  
https://github.com/sul-dlss/sul-requests/blob/main/app/models/folio/pickup_destination.rb#L30 calls 
https://github.com/sul-dlss/sul-requests/blob/main/app/models/folio/service_point.rb#L28 to get the library code
which calls https://github.com/sul-dlss/sul-requests/blob/main/app/models/folio/service_point.rb#L28 to get the library id from the location associated with this service point.

Since there is no location, the object is nil, and trying to get the library_id from a nil object returns an error.

**Comment by hudajkhan** [comment]
Relates to https://github.com/sul-dlss/sul-requests/tree/handleNoLibrary
