### ISSUE TITLE
Add messages to forms

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#181]
### Context Note
![context-note](https://cloud.githubusercontent.com/assets/96776/8136650/87825b06-10f2-11e5-9e1e-3bd01470ae3f.png)

### Destination Note
![destination-note](https://cloud.githubusercontent.com/assets/96776/8136649/8782109c-10f2-11e5-8aef-9ee424aa6a96.png)

**Comment by jvine** [comment]
Context note is dead.

### Destination note

* If the origin library has "LIBRARY_INSTRUCTIONS" in SearchWorks, insert the instructions here.
(Currently only SPEC.)

  * Current text in SW:
![screen shot 2015-07-15 at 1 20 41 pm](https://cloud.githubusercontent.com/assets/6945691/8709014/5cfcc940-2af4-11e5-8efa-36984c12b3f2.png)

  * and how it would look in Requests:
![screen shot 2015-07-15 at 1 12 30 pm](https://cloud.githubusercontent.com/assets/6945691/8709017/5faf6e22-2af4-11e5-9b07-4353b3ac6970.png)


* Otherwise, for location_specific_pickup_libraries, insert the location translation here.

  * Current text in SW:
![screen shot 2015-07-15 at 1 18 51 pm](https://cloud.githubusercontent.com/assets/6945691/8709027/6f3de698-2af4-11e5-9c6c-0ef90ca0e70e.png)

  * and how it would look in Requests:
![screen shot 2015-07-15 at 1 18 23 pm](https://cloud.githubusercontent.com/assets/6945691/8709031/72dfc6cc-2af4-11e5-8bac-f03e1bab9f69.png)

**Comment by jvine** [comment]
(Note that this may seem dorky with the current text, but it's being edited as a separate task.)

**Comment by jkeck** [comment]
Closed by #257
