### ISSUE TITLE
When FOLIO is down (or flaky) should we display a different user message?

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-requests#1964]
On Dec. 5, 2023 when FOLIO was having "issues", we received a user report (submitted via a staff member in Access Services) that they were seeing the following error message when trying to submit a request:

<img width="533" alt="image" src="https://github.com/sul-dlss/sul-requests/assets/14897546/aa1f8645-3fdb-4ec0-8b57-c94f98fe76fa">

It's unknown what error state FOLIO was in when the user received this message, but it seems like we could improve the statement here. A question I have is do we have different states that we should be accounting for in our user messaging? or is there really just one error state and user message we should display?

**Comment by dbranchini** [comment]
If it's just one error state (that FOLIO is unreachable or down), then I suggest the following. "Sorry, we're experiencing some technical difficulties. We are aware of the issue and are working to fix it. Please try again later."

**Comment by dbranchini** [comment]
After discussing this with @saseestone, we decided on the following:

Apologies, our systems are down. Please check the [system status](https://library-status.stanford.edu/) or try again later. If the issue persists, please [report it](https://searchworks.stanford.edu/feedback).

NOTE: Ideally, the report is link is dynamic - if SW is up, it goes there, if SW is down, then it goes to the library website contact us page - https://library.stanford.edu/contact-us.

**Comment by jcoyne** [comment]
Requests has no way of knowing if searchworks is "up" (consider that it may be partially degraded), so I think we just need to go to the library website.

**Comment by jcoyne** [comment]
@dbranchini what about the visual design?  Do you want to just keep the existing design and put the new message in the box?

**Comment by dbranchini** [comment]
Ideally, this message sits within the site's header/footer.

**Comment by jcoyne** [comment]
@dbranchini yes, that would be helpful

**Comment by dbranchini** [comment]
Mockup - https://www.figma.com/proto/W3GIkPyGLeO5xMojmkZuTX/SearchWorks?page-id=0%3A1&type=design&node-id=2-2&viewport=-1037%2C1269%2C0.47&t=BwVS9PhJboh1aoVR-1&scaling=min-zoom&starting-point-node-id=2%3A2&show-proto-sidebar=1&mode=design

I'm not sure if SearchWorks or Requests already has an alert/messaging style. If it does, it might be best to look more closely at how this aligns or does not align with that. Otherwise, the above mockup has the following styles:

Alert heading:
//essentially H1 except I used a 400 weight to contrast better against the light red background
color: var(--Primary-Cardinal-red---Dark, #820000);
font-family: Source Sans 3;
font-size: 2rem;
font-style: normal;
font-weight: 400;
line-height: 2.5rem; /* 125% */

Alert icon:
https://fontawesome.com/icons/triangle-exclamation?f=classic&s=solid

Alert text:
color: var(--Primary-Black-100, #2E2D29);
font-family: Source Sans 3;
font-size: 1.25rem;
font-style: normal;
font-weight: 400;
line-height: 1.75rem; /* 140% */

Alert links:
color: var(--Web-Interactive-Digital-blue-Base, #006CB8);
font-family: Source Sans 3;
font-size: 1.25rem;
font-style: normal;
font-weight: 400;
line-height: 1.75rem;
text-decoration-line: underline;

Container:
padding: 3rem 4rem;
border-radius: 0.25rem;
border: 1px solid var(--Primary-Cardinal-red---Dark, #820000);
background: rgba(140, 21, 21, 0.05); (Cardinal-red at 5%)

Please let me know if this format isn't helpful or you need something different. Also, if there are predefined styles that are close, I'm okay with using those instead.
