### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/sul-requests#2194]
Present all dates in a consistent format. There are three dates presented in the requests app, and all three are seen on the screenshot below:

Due date, Pickup date, and Not needed after date

![Image](https://github.com/sul-dlss/sul-requests/assets/6816624/5eb7834c-807c-4dba-8b46-14d45b291b1b)

**Comment by thatbudakguy** [comment]
It looks like the date format on the date selector (the "not needed after" date) can't be customized, because `<input type="date">` elements [read the date format from the user's browser automatically](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value), so we can't change it.
