### ISSUE TITLE
Disable non-scannable items in the item selector when the request is a scan

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sul-requests#2246]
We need to show the user a message to indicate what's going on, otherwise switching between page/scan would result in some items in the selector just disappearing without explanation.

**Comment by dnoneill** [comment]
Can we get some examples of this if it exists?

**Comment by saseestone** [comment]
I think this scenario can't exist. "Scanable" is set at the location level, and so is the item picker. Even items in "unavailable" item statuses (e.g. "In process" or "On order") are still considered "scanable" because we send the request off to ILLiad for a partner library.

Am I missing something?

**Comment by cbeer** [comment]
Scanning also uses the item's material type to determine eligibility. I'm not sure how likely it is there's an instance record in SAL3 with scannable and non-scannable holding, but it seems like something that might happen?

**Comment by cbeer** [comment]
I think we determined this scenario doesn't exist in FOLIO (and, it t urns out, we're not showing the scan option unless all the item types are scannable.)
