### ISSUE TITLE
Item w 2 barcodes, no item selector

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#289]
This item has 2 volumes w separate barcodes, but I don't get a selector.
https://sw-webapp-sandbox-b.stanford.edu/view/10768068

(Also don't understand why I don't get a scan option?)

![screen shot 2015-08-13 at 4 17 53 pm](https://cloud.githubusercontent.com/assets/6945691/9264118/b1871ae8-41d7-11e5-9dcf-03ad8684fb32.png)

**Comment by jkeck** [comment]
This was caused by the sandbox and the availability API pointing at different indexes.  Now that they are both pointing at the same place we are getting the scan choice and an item selector w/ 2 call numbers (the index the API was pointing at when the above screenshot was taken only had no items in STACKS which makes sense).
