### ISSUE TITLE
Error on clicking "not you"

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#290]
Okay. This item:
https://sw-webapp-sandbox-b.stanford.edu/view/10260761
technically shouldn't have a scan option, but it does. Don't know if that's relevant.

Be logged in.
Select Scan
Leave title (required) blank
Click SEnd request
You'll get the "can't be blank" error
Click "not you"
You'll get this:

![screen shot 2015-08-13 at 4 38 41 pm](https://cloud.githubusercontent.com/assets/6945691/9264361/66a698ac-41da-11e5-9eb0-1294834c40c7.png)

Note that you have to make the validation error first.

**Comment by jkeck** [comment]
This is happening because the logout path uses the referrer param or history to redirect after logout.  When you submit the form and get a validation error like this you end up viewing the form at the posted `/scans` route.  However; the redirect will be a GET request (`GET /create` routes to `ScansController#index` which does not exist).

We either need to do a better job of not allowing users to get a legitimate validation error like this OR redirect them to the `new` action with the form validation errors to feedback to the user.  (alternatively we could have the `Not you?` link explicitly pass a `referrer` param to redirect to the `new` form)
