### ISSUE TITLE
Success page shows a diff name than I entered 

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#292]
Request something that allows name + email.
Put some random name plus an email address.
Get back confirmation, fine.

Request something else. 
Put a different name but same email address as above.
Get back confirmation showing the first name you entered.

I think we need to consider name + email as unique, not just email.

**Comment by jkeck** [comment]
Although not necessarily noticeable by the user, those who submit requests via library ID will also have an unintended consequence in the database since the user is looked up via webauth ID or email address (which the library ID user has neither).  We should address both of these issues at the same time as I think they're in the same method.

https://github.com/sul-dlss/sul-requests/blob/master/app/models/request.rb#L76-L83
