### ISSUE TITLE
Add background workers for requests

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#587]
Should this reside locally on the requests VMs or on a separate VM?

The worker basically executes long-running HTTP API calls.  It takes an active record object as a parameter and needs to update the active record object with the results from the HTTP response.

**Comment by jkeck** [comment]
Sizing a 13 because this will most likely take off/on contact hours as we figure it out.

**Comment by ndushay** [comment]
created SAR-3285 asking for Redis to be added to requests-dev and requests-stage.

I spoke briefly to Erin and she agrees that for our very simple jobs (do an http request to symphony web services url) we should be fine running on the same VM as the rails app.  

We need to ensure it doesn’t create resource contention (fill up tmp space, eat too much CPU, etc.).

The dispatch team has just implemented something like this, except their background job is triggered by a rake task rather than a rails app.

**Comment by ndushay** [comment]
Redis is now on requests-dev and requests-stage

**Comment by jkeck** [comment]
I believe this was on the whiteboard, but we'll want to ensure that when mediators approve items they are not done as background jobs.  This is because they're already kind-of in the background as an ajax request by the mediator, and moving to the background job will actually make the process slower to respond to mediators.

**Comment by ndushay** [comment]
SAR-3323   for adding Redis to requests-prod
