### ISSUE TITLE
Address success/status page issues for Scan requests

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#679]
@jvine please fill out more details

**Comment by jvine** [comment]
Stage
![screen shot 2016-11-30 at 11 53 03 am](https://cloud.githubusercontent.com/assets/6945691/20768709/c30351fa-b6f3-11e6-88b9-17297bad0335.png)

Prod
![screen shot 2016-11-30 at 11 52 47 am](https://cloud.githubusercontent.com/assets/6945691/20768719/cbb45fec-b6f3-11e6-909a-fb7a540b0932.png)

- [ ] Missing "Request complete" at the top
- [ ] "Default" in help-block instead of "(We've sent a copy of this request to your email.)"
- [ ] Some styling for `.success-page .requested-by` has gone missing - it needs `color: #8c1515;` and     `font-weight: 300;`
- [ ] Bonus: remove the "Deliver to" label for scans (but this is present in prod)
