### ISSUE TITLE
Max items limit is not actually being applied

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#715]
Special Collections requests have a maximum of 5 items that can be requested at one time. The UI isn't working correctly here. Select 5 items, and the alert appears - good. But then if you continue clicking in the list - the checkbox will not be checked, the row will not be highlighted, but the items will be added to the list of selected items below the scrolling box, and the items are added to the actual request. 

Example of a request that got more than 5:  https://requests.stanford.edu/mediated_pages/102851/status

A sample record with lots of items:
https://searchworks.stanford.edu/view/4085328

![screen shot 2017-06-14 at 10 43 12 am](https://user-images.githubusercontent.com/6945691/27146837-82b62a32-50ef-11e7-829d-23c450e47814.png)

Intended behaviour once user reaches 5 items:
- display the alert
- prevent further selections in the scrolling list
- do not add any further items to the selected list

**Comment by camillevilla** [comment]
@jvine would it be ok if I split this into another ticket? It took me a while to deal with some unexpected behavior around selecting items that have been filtered down by `Search item list`. It's working now, but I haven't been able to get back-forward cache behavior to work properly. 

I did some more digging around and it looks like this bug was slipping through tests too (see screenshots below). I think it's probably important user behavior (e.g. if the request times out, a user doesn't want to fill out the form from scratch), but my PR(#717) will at least prevent them from submitting too many items.

Issues:
- Maximum limit message disappears
- User is able to select additional items

## Before request submission
![1](https://user-images.githubusercontent.com/5402927/27247088-b5453472-52aa-11e7-9657-e4fa546fe4ec.png)

## After request submission + clicking on the 'Back' button

![3](https://user-images.githubusercontent.com/5402927/27247098-c22cadd2-52aa-11e7-8917-477e37ab35fb.png)
