### ISSUE TITLE
Clicking on disabled `Send Request` button prevents submitting valid non-SUNet requests

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-requests#724]
Found this bug while doing more work on #722 / mysterious Poltergeist issues.
I'm not sure why this bug is failing more consistently on Travis (and now locally).

## Single item example

![single_item_bug](https://user-images.githubusercontent.com/5402927/27450751-905feeea-5741-11e7-9d86-65643deff88f.gif)

## Multiple item example

![multiple_item_bug](https://user-images.githubusercontent.com/5402927/27450763-99d3c190-5741-11e7-8533-0938c9187f02.gif)

**Comment by jkeck** [comment]
This appears to be caused by [a bug](https://github.com/twbs/bootstrap/issues/20511) in Bootstrap's tooltip library.

I believe it's because we [destroy the tooltip](https://github.com/sul-dlss/sul-requests/blob/12a85849f31b99dd1d9872235fd8be320ce2d985/app/assets/javascripts/additional_form_validation.js#L25) once the form passes validation.  This then stops javascript propagation and the rest of the `enableButton` function doesn't execute.

We could keep the tooltip even if the form had passed validation (which only shows up on hover) and this would stop happening.  Unfortunately, the bootstrap maintainer's proposed solution is to update to bootstrap 4, which isn't going to happen at this time.
