### ISSUE TITLE
Implement Date Picker Widget

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#90]
Use the date picker identified by #14

**Comment by jvine** [comment]
The essential issue for all users with the date picker is to not allow them to select a date that is not available:

* not before the earliest estimate
* not on a day the destination library will be closed

Can we do something similar to the "estimated delivery" feedback for this field, rather than trying to control the selection via a date picker?

**Comment by jvine** [comment]
For "Planned date of use" add min date = earliest delivery date, e.g.:
```
<input class="form-control" type="date" name="request[needed_date]" 
id="request_needed_date" min="2015-07-17">
```
