### ISSUE TITLE
Duplicate cancel link on intro step

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#984]
The intro page for paging requests has 2 cancel links - one on the popup and one in the content.

<img width="607" alt="Screen Shot 2020-06-03 at 4 11 10 PM" src="https://user-images.githubusercontent.com/6945691/83697925-fb7a1600-a5b4-11ea-9749-d0e5681bafe5.png">

This is an okay alternative if it avoids having to change the outer container:  

- remove the link that's beside the parallel button, and 
- left-align the button.

Also note that the link styling inside the iframe should match the container (and SW) - blue with no underline.

<img width="610" alt="Screen Shot 2020-06-03 at 4 15 02 PM" src="https://user-images.githubusercontent.com/6945691/83698147-8ce98800-a5b5-11ea-979f-ef5770cc08ec.png">

**Comment by jkeck** [comment]
We will have to keep the outer cancel because that comes from the modal in SW (and needs to remain there).

I've removed the cancel button in the form and left-aligned the button.  I am putting the cancel link in for non-modal contexts (e.g. I ask to open the request link in a new tab). that will just link to the SW record that was being requested.

**Comment by jkeck** [comment]
The other issue mentioned, the link text, since this is in requests, we're getting the request's link styling (w/ the underline).

Should we change request link styling, or just override link styling for the overlays (for now)?

**Comment by jvine** [comment]
Updating Request link styling to match our current style would be ideal.
